name: Build dev container images

# Add concurrency configuration to handle multiple pushes
concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    # Runs at 02:00 UTC every day
    - cron: "0 2 * * *"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
      - "**.md"
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/workflows/**"
      - "**.md"
    branches:
      # Only run on push to main branch
      - main

jobs:
  golangci:
    uses: ./.github/workflows/golangci-lint.yml

  build-and-push-docker-image:
    needs: golangci
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate downcase repository name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Tags for both Docker and Podman users
          # Standard tags for Docker users
          # Podman-prefixed tags for easier discovery by Podman users
          # Same OCI image, just different tags for user convenience
          tags: |
            ghcr.io/${{ env.REPO }}:dev
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
            ghcr.io/${{ env.REPO }}:podman-dev
            ghcr.io/${{ env.REPO }}:podman-${{ github.sha }}
          platforms: linux/arm64, linux/amd64
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ env.REPO }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=ghcr.io/${{ env.REPO }}:buildcache,mode=max
          provenance: false
          build-args: |
            BUILDKIT_INLINE_CACHE=1
